name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Setup env
        run: |
          touch .env
          echo VUE_APP_API_KEY=${{ secrets.VUE_APP_API_KEY }} >> .env
          echo VUE_APP_BASE_URL=${{ secrets.VUE_APP_BASE_URL }} >> .env
          echo VUE_APP_GEOCODER=${{ secrets.VUE_APP_GEOCODER }} >> .env
          echo VUE_APP_GET_IMG_URL=${{ secrets.VUE_APP_GET_IMG_URL }} >> .env

      - name: Build
        run: npm run build
        env:
          VUE_APP_API_KEY: ${{ secrets.VUE_APP_API_KEY }}
          VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}
          VUE_APP_GEOCODER: ${{ secrets.VUE_APP_GEOCODER }}
          VUE_APP_GET_IMG_URL: ${{ secrets.VUE_APP_GET_IMG_URL }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist