name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VUE_APP_API_KEY: ${{ secrets.VUE_APP_API_KEY }}
          VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}
          VUE_APP_GET_IMG_URL: ${{ secrets.VUE_APP_GET_IMG_URL }}
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        run: echo ${{ secrets.VUE_APP_API_KEY }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist